# Auto-label PRs based on changed files

"frontend":
  - changed-files:
      - any-glob-to-any-file:
          - "components/**/*"
          - "pages/**/*"
          - "layouts/**/*"
          - "assets/**/*"
          - "public/**/*"

"backend":
  - changed-files:
      - any-glob-to-any-file:
          - "server/**/*"
          - "prisma/**/*"

"database":
  - changed-files:
      - any-glob-to-any-file:
          - "prisma/**/*"
          - "**/*.prisma"

"authentication":
  - changed-files:
      - any-glob-to-any-file:
          - "server/api/auth/**/*"
          - "middleware/auth*"
          - "schemas/auth*"

"api":
  - changed-files:
      - any-glob-to-any-file:
          - "server/api/**/*"

"config":
  - changed-files:
      - any-glob-to-any-file:
          - "*.config.*"
          - ".env*"
          - "nuxt.config.*"
          - "tailwind.config.*"
          - "app.config.*"

"dependencies":
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "package-lock.json"
          - "pnpm-lock.yaml"
          - "yarn.lock"

"documentation":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"
          - ".github/**/*.md"

"ci/cd":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**/*"
          - ".husky/**/*"
          - ".eslintrc.*"
          - ".prettierrc*"

"ui/ux":
  - changed-files:
      - any-glob-to-any-file:
          - "components/**/*"
          - "assets/css/**/*"
          - "layouts/**/*"

"testing":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.test.*"
          - "**/*.spec.*"
          - "tests/**/*"
          - "test/**/*"
